spring:
  datasource:
    url: jdbc:postgresql://postgres-postgresql.default.svc.cluster.local:5432/orm_apple_device
    username: postgres
    password: LI5QP6AqXA
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

device:
  images:
    url: http://ms-device-image-loadbalancer/device_images