spring:
  datasource:
    url: jdbc:postgresql://postgres-postgresql.default.svc.cluster.local:5432/orm_user
    username: postgres
    password: LI5QP6AqXA
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
  rabbitmq:
    host: rabbit-rabbitmq.default.svc.cluster.local
    port: 5672
    username: user
    password: bpWJ7c3WBJ

queue:
  mail-sender-q: Mail_Sender_Q