apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-apple-device-deployment
  labels:
    app: ms-apple-device
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-apple-device
  template:
    metadata:
      labels:
        app: ms-apple-device
    spec:
      containers:
        - name: ms-apple-device
          image: drampel/ms-apple-device
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5