package az.apple_corporation.appleDevice.model;

public enum SpecificationType {
    DIMENSIONS, WEIGHT, SIM_CARD_TYPE, SIM_QUANTITY, MOBILE_NETWORKS, OPERATING_SYSTEM, PROCESSOR, BUILT_IN_MEMORY,
    RAM_SIZE, SCREEN_TYPE, DIAGONAL, SCREEN_RESOLUTION, MAIN_CAMERA, FRONT_CAMERA, WI_FI, BLUETOOTH, BATTERY_CAPACITY
}