server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orm_user
    username: postgres
    password: user
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml