apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-mail-sender-deployment
  labels:
    app: ms-mail-sender
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-mail-sender
  template:
    metadata:
      labels:
        app: ms-mail-sender
    spec:
      containers:
        - name: ms-mail-sender
          image: drampel/ms-mail-sender
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5