apiVersion: v1
kind: Pod
metadata:
  name: ms-mail-sender
  labels:
    app: ms-mail-sender
spec:
  containers:
  - image: drampel/ms-mail-sender
    name: ms-mail-sender
    ports:
    - containerPort: 8080
      protocol: TCP